# Generated by Django 4.2.10 on 2024-03-01 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name=uuid.UUID('25e66f76-e1a3-4b1e-a30c-385459dfa7cd'))),
                ('creted_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=30)),
                ('gender', models.CharField(max_length=10)),
                ('disease', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name=uuid.UUID('25e66f76-e1a3-4b1e-a30c-385459dfa7cd'))),
                ('creted_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=100)),
                ('expiry_date', models.CharField(max_length=50)),
                ('weight_in_ML', models.IntegerField(default=50)),
                ('use_in_disease', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
