# Generated by Django 4.1.13 on 2024-03-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='weight_in_ML',
            new_name='weight_in_ML_or_gram',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_available',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
