# Generated by Django 4.1.13 on 2024-03-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_system', '0002_rename_weight_in_ml_medicine_weight_in_ml_or_gram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='weight_in_ML_or_gram',
            new_name='weight_in_ml_or_mg',
        ),
    ]
